[package]
name = "project"
version = "1.70.0"
edition = "2021"

[dependencies]
util = {path = "/mnt/Master/Documents/Rust/Rust_Generics"}
pyo3 = { version = "0.18.0", features = ["auto-initialize"] }
